name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"features":["python latest","ssl","ssl
            always"],"nginx":{"root":"public_html/public","passenger":{"enabled":"on","python":".pyenv/shims/python"}},"commands":["test
            -f requirements.txt && pip install -r $_ || pip install django","sed
            -i \"s/ALLOWED_HOSTS = \\[\\]/ALLOWED_HOSTS = \\['${DOMAIN}'\\]/g\"
            ipl_cricket/settings.py","echo \"from ipl_cricket.wsgi import
            application\" > passenger_wsgi.py","python manage.py migrate ||
            true"],"source":{"url":"ssh://git@github.com/KadeSatrya/ipl_cricket.git","credentials":{"github":{"ssh":"-----BEGIN
            OPENSSH PRIVATE
            KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS\n1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQS/KxO+STpO03UbyDiWejw0Qr/7h3w5\nTb06g/E6NmT23nh+n0eXI7gQkJ9syF9UQZ2YaHtJrolFSUSosP0td2FBAAAAqFPSEaxT0h\nGsAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBL8rE75JOk7TdRvI\nOJZ6PDRCv/uHfDlNvTqD8To2ZPbeeH6fR5cjuBCQn2zIX1RBnZhoe0muiUVJRKiw/S13YU\nEAAAAhAIuedF80vTBXDtb2D0PJwRbDzMQVp7bLuOPgdmwmmQ4mAAAADmdpdEBnaXRodWIu\nY29tAQ==\n-----END
            OPENSSH PRIVATE KEY-----\n"}}}}
